# Generated by Django 5.2 on 2025-04-28 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_department_remove_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Contact must be a valid phone number with 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must be alphanumeric (letters and numbers only).', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
