# Generated by Django 5.2 on 2025-04-28 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_contact_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must only contain letters and spaces.', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
