# Generated by Django 5.2 on 2025-04-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_1', models.TimeField(blank=True, null=True)),
                ('out_1', models.TimeField(blank=True, null=True)),
                ('in_2', models.TimeField(blank=True, null=True)),
                ('out_2', models.TimeField(blank=True, null=True)),
                ('in_3', models.TimeField(blank=True, null=True)),
                ('out_3', models.TimeField(blank=True, null=True)),
                ('in_4', models.TimeField(blank=True, null=True)),
                ('out_4', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
